name: ARC Test Containers Workflow
run-name: Run test workflow on ${{ inputs.arc_name }}
on:
  workflow_dispatch:
    inputs:
      arc_name:
        description: 'Target ARC name used for `runs-on` in job'
        required: true
jobs:
  arc-runner-job:
    strategy:
      fail-fast: false
      matrix:
        job: [1, 2, 3]
    runs-on: ${{ inputs.arc_name }}
    container: bitnamisecure/git:latest
    services:
      redis:
        image: redis:alpine
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World!" >> $GITHUB_STEP_SUMMARY
